apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:5.7
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              value: mypass1234
            - name: MYSQL_DATABASE
              value: achatdb
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mynamespace
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: "TCP"
      port: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mohamedamine1/saadbguir:backend
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{
                "spring.datasource.url": "jdbc:mysql://mysql-service:3306/achatdb?useSSL=false",
                "spring.datasource.username": "root",
                "spring.datasource.password": "mypass1234",
                "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
                "spring.jpa.hibernate.ddl-auto": "update"
              }'

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mynamespace
spec:
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      port: 8089

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mohamedamine1/saadbguir:frontend
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mynamespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: "TCP"
      port: 80
