apiVersion: apps/v1
kind: Deployment
metadata:
  name: achat-deployment
spec:
  selector:
    matchLabels:
      app: achat
  replicas: 2
  template:
    metadata:
      labels:
        app: achat
    spec:
      containers:
        - name: backend-spring
          image: mohamedamine1/saadbguir:backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089

        - name: frontend-angular
          image: mohamedamine1/saadbguir:frontend  # Replace with the actual image for your frontend application
          ports:
            - containerPort: 80  # The port for your frontend container

        - name: mysqldb
          image: mysql:5.7
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_ROOT_PASSWORD
              value: mypass1234
            - name: MYSQL_DATABASE
              value: achatdb
          ports:
            - containerPort: 3306

      volumes:
        - name: mysql-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: achat-service
spec:
  selector:
    app: achat
  ports:
    - name: backend-port
      protocol: "TCP"
      port: 8089
      targetPort: 8089
    - name: frontend-port
      protocol: "TCP"
      port: 80
      targetPort: 80  # Match the targetPort to the frontend container's port
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
spec:
  selector:
    app: achat
  ports:
    - name: mysql-port
      protocol: "TCP"
      port: 3306
      targetPort: 3306  # Match the targetPort to the mysqldb container's port
