apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:5.7
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              value: mypass1234
            - name: MYSQL_DATABASE
              value: achatdb
          ports:
            - containerPort: 3306
